import {
  AUDIT_UI_FLAG_DETAILS,
  CHECKLIST_UPDATE_FLAG_DETAILS,
  CHECKLIST_VERIFY_FLAG_DETAILS,
  GATE_STAGE_OPTIONS,
  GATES_PLAN_FLAG_DETAILS,
  GATES_STATUS_FLAG_DETAILS,
  INIT_FLAG_DETAILS,
  MIGRATE_LEGACY_FLAG_DETAILS,
  MIGRATE_MAP_FLAG_DETAILS,
  PR_BODY_FLAG_DETAILS,
  PR_GATE_FLAG_DETAILS,
  PR_REVIEW_PUBLISH_FLAG_DETAILS,
  PR_VIEW_FLAG_DETAILS,
  PR_REVIEW_AGENT_VALUES,
  REVIEW_AGENT_VALUES,
  REVIEW_GATE_FLAG_DETAILS,
} from './command_flag_details.js';
import { defineExecutorCommands } from './command_definition.js';
import { RUN_COMMAND_DEFINITIONS } from './command_catalog_run.js';

export const CONFIG_ERROR_KINDS = ['missing', 'invalid', 'unknown', 'duplicate'];
export const COMMON_ERROR_KINDS = ['parse-error', 'config-error', 'github-error', 'repository-state-error'];

const INIT_FLAGS = INIT_FLAG_DETAILS.map(flag => flag.name);

const COMMAND_DEFINITIONS = [
  {
    name: 'doctor',
    description: 'Check runtime environment, git, GitHub CLI, repository state, worktree policy, and config health for Executor.',
    args: [],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    externalServices: ['github'],
    stableErrorKinds: ['config-error', 'github-error', 'repository-state-error', ...CONFIG_ERROR_KINDS],
    examples: ['aie doctor', 'aie doctor --json'],
  },
  {
    name: 'status',
    description: 'Report trusted continuation state across providers, queue, repository, review, and gates. Read-only.',
    args: [],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    externalServices: ['github'],
    stableErrorKinds: ['config-error', 'github-error', 'repository-state-error', 'review-state-unavailable', ...CONFIG_ERROR_KINDS],
    examples: ['aie status', 'aie status --json'],
  },
  {
    name: 'schema',
    description: 'Emit machine-readable description of implemented CLI commands, arguments, flags, and capabilities for agents.',
    args: [],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    stableErrorKinds: ['schema-generation-error'],
    examples: ['aie schema --json'],
  },
  {
    name: 'labels',
    description: 'Manage the Executor-owned priority, status, and component labels in the current GitHub repository.',
    args: [],
    flags: ['--help'],
    mutationTargets: [],
    supportsJson: false,
    supportsDryRun: false,
    examples: ['aie labels setup --dry-run'],
  },
  {
    name: 'labels setup',
    description: 'Create or update the configured Executor priority, status, and component labels idempotently. This command mutates GitHub.',
    args: [],
    flags: ['--json', '--dry-run', '--help'],
    mutationTargets: ['github'],
    supportsJson: true,
    supportsDryRun: true,
    examples: ['aie labels setup --dry-run', 'aie labels setup --json', 'aie labels setup'],
  },
  {
    name: 'queue',
    description: 'Display the ordered issue queue (effective status from labels + dependencies).',
    args: [],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    examples: ['aie queue', 'aie queue --json'],
  },
  {
    name: 'next',
    description: 'Select the next issue to work on (resume single S-InProgress or first ready).',
    args: [],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    examples: ['aie next', 'aie next --json'],
  },
  {
    name: 'start',
    description: 'Start or resume issue work by applying lifecycle labels after queue, blocker, and repository safety checks. This command can mutate GitHub.',
    args: ['issue'],
    flags: ['--json', '--dry-run', '--no-assign', '--no-comment', '--help'],
    mutationTargets: ['github'],
    supportsJson: true,
    supportsDryRun: true,
    examples: ['aie start', 'aie start next', 'aie start 93 --dry-run', 'aie start #93 --json', 'aie start 93 --no-assign --no-comment'],
  },
  {
    name: 'switch',
    description: 'Pause the current in-progress issue and start a target issue after queue, blocker, and repository safety checks. This command can mutate GitHub.',
    args: ['issue'],
    flags: ['--json', '--dry-run', '--from', '--no-assign', '--no-comment', '--help'],
    mutationTargets: ['github'],
    supportsJson: true,
    supportsDryRun: true,
    examples: ['aie switch 94 --dry-run', 'aie switch #94 --json', 'aie switch 94 --from 93', 'aie switch 94 --no-assign --no-comment'],
  },
  {
    name: 'complete',
    description: 'Complete post-merge issue work, clean lifecycle labels, close open issues, and refresh dependents. This command can mutate GitHub.',
    args: ['issue'],
    flags: ['--json', '--dry-run', '--check-only', '--force', '--help'],
    mutationTargets: ['github'],
    supportsJson: true,
    supportsDryRun: true,
    supportsCheckOnly: true,
    examples: ['aie complete 93 --check-only', 'aie complete 93 --dry-run', 'aie complete #93 --json', 'aie complete 93 --force'],
  },
  {
    name: 'checklist',
    description: 'Inspect and evidence-verify durable GitHub issue checklist state used by Executor completion.',
    args: [],
    flags: ['--help'],
    mutationTargets: [],
    supportsJson: false,
    supportsDryRun: false,
    examples: ['aie checklist verify 93 --index 2 --prompt', 'aie checklist verify 93 --index 2 --evidence evidence.json --state checked'],
  },
  {
    name: 'checklist update',
    description: 'Perform one unchecked maintenance mutation on a GitHub issue task-list checkbox while preserving unrelated issue body text. Checking acceptance criteria requires checklist verify.',
    args: ['issue'],
    flags: CHECKLIST_UPDATE_FLAG_DETAILS.map(flag => flag.name),
    flagDetails: CHECKLIST_UPDATE_FLAG_DETAILS,
    mutationTargets: ['github'],
    supportsJson: true,
    supportsDryRun: true,
    externalServices: ['github'],
    stableErrorKinds: ['parse-error', 'github-error', 'checklist-ambiguous', ...CONFIG_ERROR_KINDS],
    examples: ['aie checklist update 93 --index 2 --state unchecked --dry-run', 'aie checklist update 93 --index 2 --state unchecked --json'],
  },
  {
    name: 'checklist verify',
    description: 'Verify exactly one acceptance checklist criterion with prompt-backed evidence before checking it.',
    args: ['issue'],
    flags: CHECKLIST_VERIFY_FLAG_DETAILS.map(flag => flag.name),
    flagDetails: CHECKLIST_VERIFY_FLAG_DETAILS,
    mutationTargets: ['github'],
    supportsJson: true,
    supportsDryRun: true,
    externalServices: ['github'],
    stableErrorKinds: ['parse-error', 'github-error', 'acceptance-evidence-error', ...CONFIG_ERROR_KINDS],
    examples: ['aie checklist verify 93 --index 2 --prompt', 'aie checklist verify 93 --index 2 --dry-run --json', 'aie checklist verify 93 --index 2 --evidence evidence.json --state checked'],
  },
  {
    name: 'init',
    description: 'Initialize Executor config and managed instruction files in a repository. This command mutates local files.',
    args: ['target'],
    flags: INIT_FLAGS,
    flagDetails: INIT_FLAG_DETAILS,
    mutationTargets: ['local-files'],
    supportsJson: true,
    supportsDryRun: true,
    examples: ['aie init . --dry-run', 'aie init . --json', 'aie init . --defaults --yes', 'aie init . --tool all --naming-rules', 'aie init . --tool opencode --opencode-command-alias', 'aie init . --no-milestone-ordering --package-age-days 7'],
  },
  {
    name: 'gates',
    description: 'Plan and inspect configured agent-run gates without executing configured commands.',
    args: [],
    flags: ['--help'],
    mutationTargets: [],
    supportsJson: false,
    supportsDryRun: false,
    examples: ['aie gates', 'aie gates plan --dry-run', 'aie gates status --json'],
  },
  {
    name: 'gates plan',
    description: 'Show the configured gate order, command obligations, evidence expectations, and supply-chain-sensitive commands without executing gates.',
    args: [],
    flags: GATES_PLAN_FLAG_DETAILS.map(flag => flag.name),
    flagDetails: GATES_PLAN_FLAG_DETAILS,
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: true,
    stageValues: GATE_STAGE_OPTIONS,
    stableErrorKinds: ['config-error', ...CONFIG_ERROR_KINDS],
    examples: ['aie gates plan --dry-run', 'aie gates plan --stage pre-pr --json'],
  },
  {
    name: 'gates status',
    description: 'Report configured gate obligations and recorded evidence without claiming unverified success.',
    args: [],
    flags: GATES_STATUS_FLAG_DETAILS.map(flag => flag.name),
    flagDetails: GATES_STATUS_FLAG_DETAILS,
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    stageValues: GATE_STAGE_OPTIONS,
    stableErrorKinds: ['config-error', ...CONFIG_ERROR_KINDS],
    examples: ['aie gates status', 'aie gates status --json'],
  },
  {
    name: 'migrate',
    description: 'Inspect and plan safe migration from copied legacy Executor helpers to package-backed commands.',
    args: [],
    flags: ['--help'],
    mutationTargets: [],
    supportsJson: false,
    supportsDryRun: false,
    stableErrorKinds: ['migration-error'],
    examples: ['aie migrate', 'aie migrate map', 'aie migrate legacy --dry-run', 'aie migrate legacy --json'],
  },
  {
    name: 'migrate legacy',
    description: 'Audit copied scripts, old workflow docs, project commands, and instruction blocks, then explicitly apply safe instruction updates, compatibility wrappers, or cleanup.',
    args: [],
    flags: MIGRATE_LEGACY_FLAG_DETAILS.map(flag => flag.name),
    flagDetails: MIGRATE_LEGACY_FLAG_DETAILS,
    mutationTargets: ['local-files'],
    supportsJson: true,
    supportsDryRun: true,
    stableErrorKinds: ['config-error', 'migration-error', 'repository-state-error', ...CONFIG_ERROR_KINDS],
    migrationModeValues: ['audit-plan', 'apply-plan', 'apply-result'],
    migrationActionValues: ['remove', 'replace', 'preserve', 'skip'],
    migrationConfidenceValues: ['high', 'medium', 'review-required'],
    examples: ['aie migrate legacy', 'aie migrate legacy --dry-run', 'aie migrate legacy --cleanup --dry-run', 'aie migrate legacy --install-wrappers --apply --dry-run', 'aie migrate legacy --apply --instruction AGENTS.md --force'],
  },
  {
    name: 'migrate map',
    description: 'Show product-generic mappings from legacy workflow categories to package-backed Executor commands.',
    args: [],
    flags: MIGRATE_MAP_FLAG_DETAILS.map(flag => flag.name),
    flagDetails: MIGRATE_MAP_FLAG_DETAILS,
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    stableErrorKinds: ['migration-error'],
    examples: ['aie migrate map', 'aie migrate map --json'],
  },
  {
    name: 'audit',
    description: 'Plan manual audit helpers for repository changes that need real local evidence.',
    args: [],
    flags: ['--help'],
    mutationTargets: [],
    supportsJson: false,
    supportsDryRun: false,
    examples: ['aie audit', 'aie audit ui 93 --dry-run', 'aie audit ui 93 --prepare'],
  },
  {
    name: 'audit ui',
    description: 'Plan, prepare, and check local manual UI audit evidence without uploading screenshots or claiming unverified pass/fail.',
    args: ['issue'],
    flags: AUDIT_UI_FLAG_DETAILS.map(flag => flag.name),
    flagDetails: AUDIT_UI_FLAG_DETAILS,
    mutationTargets: ['local-files'],
    supportsJson: true,
    supportsDryRun: true,
    externalServices: ['agent-browser', 'playwright-fallback'],
    stableErrorKinds: ['parse-error', 'config-error', 'local-evidence-error', ...CONFIG_ERROR_KINDS],
    examples: ['aie audit ui 93 --dry-run', 'aie audit ui 93 --prepare', 'aie audit ui 93 --check --json'],
  },
  ...RUN_COMMAND_DEFINITIONS,
  {
    name: 'review',
    description: 'Render review-agent gate prompts and evidence requirements without invoking host-only reviewers.',
    args: [],
    flags: ['--help'],
    mutationTargets: [],
    supportsJson: false,
    supportsDryRun: false,
    examples: ['aie review', 'aie review gate 93 --prompt', 'aie review gate 93 --json'],
  },
  {
    name: 'review gate',
    description: 'Render the configured review-agent gate prompt, local evidence status, Oracle-style fallback, and evidence requirements without treating review output as policy.',
    args: ['issue'],
    flags: REVIEW_GATE_FLAG_DETAILS.map(flag => flag.name),
    flagDetails: REVIEW_GATE_FLAG_DETAILS,
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: true,
    externalServices: ['configured-review-agent'],
    stableErrorKinds: ['parse-error', 'config-error', 'review-evidence-error', ...CONFIG_ERROR_KINDS],
    stageValues: ['pre-pr'],
    reviewAgentValues: REVIEW_AGENT_VALUES,
    examples: ['aie review gate 93 --prompt', 'aie review gate 93 --dry-run', 'aie review gate 93 --json'],
  },
  {
    name: 'pr',
    description: 'Coordinate pull request review gates and merge-readiness checks without merging pull requests.',
    args: [],
    flags: ['--help'],
    mutationTargets: [],
    supportsJson: false,
    supportsDryRun: false,
    examples: ['aie pr', 'aie pr view 12 --json', 'aie pr body 93', 'aie pr gate 12 --dry-run'],
  },
  {
    name: 'pr view',
    description: 'Show concise pull request state for agents without raw PR comment or review payloads. Read-only.',
    args: ['pr'],
    flags: PR_VIEW_FLAG_DETAILS.map(flag => flag.name),
    flagDetails: PR_VIEW_FLAG_DETAILS,
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    externalServices: ['github'],
    stableErrorKinds: ['parse-error', 'config-error', 'github-error', 'review-state-unavailable', ...CONFIG_ERROR_KINDS],
    reviewAgentValues: PR_REVIEW_AGENT_VALUES,
    examples: ['aie pr view 12', 'aie pr view 12 --json'],
  },
  {
    name: 'pr body',
    description: 'Draft a PR body with issue closure text, configured gate state, UI audit state, local and remote review-agent evidence, and merge-readiness guidance. Read-only.',
    args: ['issue'],
    flags: PR_BODY_FLAG_DETAILS.map(flag => flag.name),
    flagDetails: PR_BODY_FLAG_DETAILS,
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    externalServices: ['github'],
    stableErrorKinds: ['parse-error', 'config-error', 'github-error', 'readiness-error', ...CONFIG_ERROR_KINDS],
    reviewAgentValues: PR_REVIEW_AGENT_VALUES,
    examples: ['aie pr body 93', 'aie pr body #93 --json'],
  },
  {
    name: 'pr gate',
    description: 'Request configured PR reviewers idempotently, validate local review evidence when configured, wait the configured duration, and inspect review state before merge.',
    args: ['pr'],
    flags: PR_GATE_FLAG_DETAILS.map(flag => flag.name),
    flagDetails: PR_GATE_FLAG_DETAILS,
    mutationTargets: ['github'],
    supportsJson: true,
    supportsDryRun: true,
    externalServices: ['github', 'github-copilot', 'cubic', 'coderabbitai', 'custom-pr-reviewer'],
    stableErrorKinds: ['parse-error', 'config-error', 'github-error', 'review-state-unavailable', ...CONFIG_ERROR_KINDS],
    reviewAgentValues: PR_REVIEW_AGENT_VALUES,
    examples: ['aie pr gate 12 --dry-run', 'aie pr gate 12 --json', 'aie pr gate 12'],
  },
  {
    name: 'pr review publish',
    description: 'Publish one evidence-backed host-run lane review comment to the configured review provider for the current PR head.',
    args: ['pr'],
    flags: PR_REVIEW_PUBLISH_FLAG_DETAILS.map(flag => flag.name),
    flagDetails: PR_REVIEW_PUBLISH_FLAG_DETAILS,
    mutationTargets: ['github'],
    supportsJson: true,
    supportsDryRun: true,
    externalServices: ['github'],
    stableErrorKinds: ['parse-error', 'config-error', 'github-error', 'local-review-malformed', 'local-review-missing', ...CONFIG_ERROR_KINDS],
    reviewAgentValues: PR_REVIEW_AGENT_VALUES,
    examples: ['aie pr review publish 12 --lane issue-compliance', 'aie pr review publish 12 --lane code-quality --issue 93 --json', 'aie pr review publish 12 --lane security --dry-run'],
  },
  {
    name: 'branch',
    description: 'Suggest, verify, and explicitly create issue branches according to repository branch policy.',
    args: [],
    flags: ['--help'],
    mutationTargets: [],
    supportsJson: false,
    supportsDryRun: false,
    examples: ['aie branch', 'aie branch suggest 93', 'aie branch check 93', 'aie branch create 93 --dry-run'],
  },
  {
    name: 'branch suggest',
    description: 'Suggest the policy-compliant issue branch name. Read-only.',
    args: ['issue'],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    examples: ['aie branch suggest 93', 'aie branch suggest #93 --json'],
  },
  {
    name: 'branch check',
    description: 'Verify whether the current branch matches the policy-compliant issue branch. Read-only.',
    args: ['issue'],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    examples: ['aie branch check 93', 'aie branch check #93 --json'],
  },
  {
    name: 'branch create',
    description: 'Create or switch to the policy-compliant issue branch after safe repository checks. This command mutates git state.',
    args: ['issue'],
    flags: ['--json', '--dry-run', '--help'],
    mutationTargets: ['git'],
    supportsJson: true,
    supportsDryRun: true,
    examples: ['aie branch create 93 --dry-run', 'aie branch create #93 --json', 'aie branch create 93'],
  },
  {
    name: 'repo',
    description: 'Inspect and prepare repository state for Executor issue execution.',
    args: [],
    flags: ['--help'],
    mutationTargets: [],
    supportsJson: false,
    supportsDryRun: false,
    examples: ['aie repo', 'aie repo prime --dry-run', 'aie repo prime --json'],
  },
  {
    name: 'repo prime',
    description: 'Prepare repository labels, minimal config, and pre-start visibility for Executor issue execution. This command can mutate GitHub labels and local config.',
    args: [],
    flags: ['--json', '--dry-run', '--yes', '--help'],
    mutationTargets: ['github', 'local-files'],
    supportsJson: true,
    supportsDryRun: true,
    examples: ['aie repo prime --dry-run', 'aie repo prime --json', 'aie repo prime --yes'],
  },
  {
    name: 'deps',
    description: 'Inspect the dependency graph of GitHub issues and synchronize status labels (S-Ready, S-Blocked, S-Blocking) from the live blocker graph. Most commands are read-only; `aie deps fix` mutates labels.',
    args: [],
    flags: ['--help'],
    mutationTargets: [],
    supportsJson: false,
    supportsDryRun: false,
    examples: ['aie deps blockers 93', 'aie deps blockers #93', 'aie deps blocking 93', 'aie deps blocking #93', 'aie deps ready', 'aie deps blocked', 'aie deps chain 93', 'aie deps graph --json', 'aie deps fix --dry-run', 'aie deps fix --json'],
  },
  {
    name: 'deps blockers',
    description: 'List direct blockers for an issue (from "Blocked by: #N" lines in the body). Read-only.',
    args: ['issue'],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    examples: ['aie deps blockers 93', 'aie deps blockers #93'],
  },
  {
    name: 'deps blocked',
    description: 'List all blocked open issues and their open blockers. Read-only.',
    args: [],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    examples: ['aie deps blocked'],
  },
  {
    name: 'deps blocking',
    description: 'List open issues blocked by a given issue (reverse of blockers). Read-only.',
    args: ['issue'],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    examples: ['aie deps blocking 93', 'aie deps blocking #93'],
  },
  {
    name: 'deps ready',
    description: 'List issues with no open blockers (ready to start). Read-only.',
    args: [],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    examples: ['aie deps ready'],
  },
  {
    name: 'deps chain',
    description: 'Report the dependency chain for an issue (recursive blockers). Read-only.',
    args: ['issue'],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    examples: ['aie deps chain 93', 'aie deps chain #93'],
  },
  {
    name: 'deps graph',
    description: 'Emit the dependency graph of open issues. Read-only.',
    args: [],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    examples: ['aie deps graph --json'],
  },
  {
    name: 'deps fix',
    description: 'Synchronize status labels (S-Ready, S-Blocked, S-Blocking) from the live dependency graph. This command mutates GitHub labels. S-InProgress issues are never changed.',
    args: [],
    flags: ['--json', '--dry-run', '--help'],
    mutationTargets: ['github'],
    supportsJson: true,
    supportsDryRun: true,
    examples: ['aie deps fix --dry-run', 'aie deps fix --json', 'aie deps fix'],
  },
  {
    name: 'view',
    description: 'Display issue context including title, state, labels, blockers, dependents, checklist, branch suggestion, and recommended next action. Read-only.',
    args: ['issue'],
    flags: ['--json', '--help'],
    mutationTargets: [],
    supportsJson: true,
    supportsDryRun: false,
    examples: ['aie view 93', 'aie view #93', 'aie view 93 --json'],
  },
] satisfies Parameters<typeof defineExecutorCommands>[0];

export const IMPLEMENTED_COMMANDS = defineExecutorCommands(COMMAND_DEFINITIONS, COMMON_ERROR_KINDS);
