// Generated by scripts/suite-pins.mjs. Do not edit.
export const adapterPackageVersions = Object.freeze({
  "@tjalve/qube-adapter-claude-code": "0.1.8",
  "@tjalve/qube-adapter-codex": "0.1.10",
  "@tjalve/qube-adapter-cursor": "0.1.2",
  "@tjalve/qube-adapter-github": "0.1.8",
  "@tjalve/qube-adapter-gitlab": "0.1.8",
  "@tjalve/qube-adapter-grok-build": "0.1.10",
  "@tjalve/qube-adapter-jenkins": "0.1.6",
  "@tjalve/qube-adapter-jira": "0.1.6",
  "@tjalve/qube-adapter-linear": "0.1.6",
  "@tjalve/qube-adapter-opencode": "0.1.7",
} as const);
