import { existsSync, lstatSync, mkdirSync, readFileSync, realpathSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import path from "node:path";

import { ADAPTER_PACKAGES, readCatalogManifests } from "./workspace-packages.mjs";

export const ADAPTER_PINS_PATH = "products/qube/src/adapter_versions.generated.ts";
const EXACT_VERSION = /^\d+\.\d+\.\d+$/;

function isOutside(root, candidate) {
  const relative = path.relative(root, candidate);
  return relative.startsWith("..") || path.isAbsolute(relative);
}

function resolveAdapterPinsPath(root, createParent = false) {
  const realRoot = realpathSync.native(root);
  const outputPath = path.resolve(root, ADAPTER_PINS_PATH);
  if (isOutside(root, outputPath)) {
    throw Object.assign(new Error(`${ADAPTER_PINS_PATH} escapes the suite root.`), { reasonCode: "unsafe-generated-path" });
  }

  const parentPath = path.dirname(outputPath);
  const parentParts = path.relative(root, parentPath).split(path.sep).filter(Boolean);
  let currentPath = root;
  for (const part of parentParts) {
    currentPath = path.join(currentPath, part);
    if (!existsSync(currentPath)) {
      if (!createParent) break;
      mkdirSync(currentPath);
    }
    const currentStat = lstatSync(currentPath);
    if (currentStat.isSymbolicLink() || !currentStat.isDirectory() || isOutside(realRoot, realpathSync.native(currentPath))) {
      throw Object.assign(new Error(`${ADAPTER_PINS_PATH} has an unsafe parent path.`), { reasonCode: "unsafe-generated-path" });
    }
  }

  if (existsSync(outputPath)) {
    const outputStat = lstatSync(outputPath);
    if (outputStat.isSymbolicLink() || !outputStat.isFile() || isOutside(realRoot, realpathSync.native(outputPath))) {
      throw Object.assign(new Error(`${ADAPTER_PINS_PATH} is not a safe regular file.`), { reasonCode: "unsafe-generated-path" });
    }
  }
  return outputPath;
}

export function renderAdapterPins(root, entries = ADAPTER_PACKAGES) {
  const packages = readCatalogManifests(root, entries)
    .map(entry => {
      if (!EXACT_VERSION.test(String(entry.version))) {
        throw Object.assign(new Error(`${entry.packageJson} must declare an exact semantic version.`), { reasonCode: "invalid-version" });
      }
      return entry;
    })
    .sort((left, right) => left.name.localeCompare(right.name));
  const rows = packages.map(entry => `  ${JSON.stringify(entry.name)}: ${JSON.stringify(entry.version)},`).join("\n");
  return `// Generated by scripts/suite-pins.mjs. Do not edit.\nexport const adapterPackageVersions = Object.freeze({\n${rows}\n} as const);\n`;
}

export function inspectAdapterPins(root, entries = ADAPTER_PACKAGES) {
  const expected = renderAdapterPins(root, entries);
  const outputPath = resolveAdapterPinsPath(root);
  const actual = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : null;
  const normalizedActual = actual?.replace(/\r\n/g, "\n") ?? null;
  return Object.freeze({
    ok: normalizedActual === expected,
    changed: normalizedActual !== expected,
    outputPath: ADAPTER_PINS_PATH,
    expected,
    failure: normalizedActual === expected ? null : `${ADAPTER_PINS_PATH} is stale. Run node scripts/suite-pins.mjs --write.`,
  });
}

function replaceGeneratedFile(outputPath, contents) {
  const temporaryPath = `${outputPath}.${process.pid}.${randomUUID()}.tmp`;
  let temporaryExists = false;
  try {
    writeFileSync(temporaryPath, contents, { encoding: "utf8", flag: "wx", mode: 0o644 });
    temporaryExists = true;
    renameSync(temporaryPath, outputPath);
    temporaryExists = false;
  } finally {
    if (temporaryExists) rmSync(temporaryPath, { force: true });
  }
}

export function writeAdapterPins(root, entries = ADAPTER_PACKAGES) {
  const inspection = inspectAdapterPins(root, entries);
  if (inspection.changed) {
    const outputPath = resolveAdapterPinsPath(root, true);
    replaceGeneratedFile(outputPath, inspection.expected);
  }
  return Object.freeze({ ...inspection, ok: true, wrote: inspection.changed });
}
