import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { ADAPTER_PACKAGES, readCatalogManifests } from "./workspace-packages.mjs";

export const ADAPTER_PINS_PATH = "products/qube/src/adapter_versions.generated.ts";
const EXACT_VERSION = /^\d+\.\d+\.\d+$/;

export function renderAdapterPins(root, entries = ADAPTER_PACKAGES) {
  const packages = readCatalogManifests(root, entries)
    .map(entry => {
      if (!EXACT_VERSION.test(String(entry.version))) {
        throw Object.assign(new Error(`${entry.packageJson} must declare an exact semantic version.`), { reasonCode: "invalid-version" });
      }
      return entry;
    })
    .sort((left, right) => left.name.localeCompare(right.name));
  const rows = packages.map(entry => `  ${JSON.stringify(entry.name)}: ${JSON.stringify(entry.version)},`).join("\n");
  return `// Generated by scripts/suite-pins.mjs. Do not edit.\nexport const adapterPackageVersions = Object.freeze({\n${rows}\n} as const);\n`;
}

export function inspectAdapterPins(root, entries = ADAPTER_PACKAGES) {
  const expected = renderAdapterPins(root, entries);
  const outputPath = path.join(root, ADAPTER_PINS_PATH);
  const actual = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : null;
  return Object.freeze({
    ok: actual === expected,
    changed: actual !== expected,
    outputPath: ADAPTER_PINS_PATH,
    expected,
    failure: actual === expected ? null : `${ADAPTER_PINS_PATH} is stale. Run node scripts/suite-pins.mjs --write.`,
  });
}

export function writeAdapterPins(root, entries = ADAPTER_PACKAGES) {
  const inspection = inspectAdapterPins(root, entries);
  if (inspection.changed) {
    const outputPath = path.join(root, ADAPTER_PINS_PATH);
    mkdirSync(path.dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, inspection.expected, "utf8");
  }
  return Object.freeze({ ...inspection, ok: true, wrote: inspection.changed });
}
